// Demo data store for OpistoHelp
// This file contains all the sample data for the application

export const demoUsers = [
  { id: 1, name: 'Mikko Virtanen', email: 'mikko@opisto.fi', avatar: '👨', balance: 45.50, rating: 4.8, completedTasks: 12, role: 'student' },
  { id: 2, name: 'Anna Koskinen', email: 'anna@opisto.fi', avatar: '👩', balance: 32.00, rating: 4.6, completedTasks: 8, role: 'student' },
  { id: 3, name: 'Jukka Nieminen', email: 'jukka@opisto.fi', avatar: '👨', balance: 15.50, rating: 4.2, completedTasks: 5, role: 'student' },
  { id: 4, name: 'Liisa Ahonen', email: 'liisa@opisto.fi', avatar: '👩', balance: 78.00, rating: 4.9, completedTasks: 20, role: 'student' },
  { id: 5, name: 'Petri Mäkinen', email: 'petri@opisto.fi', avatar: '👨', balance: 8.00, rating: 3.8, completedTasks: 3, role: 'student' },
  { id: 6, name: 'Maria Virtanen', email: 'maria@opisto.fi', avatar: '👩', balance: 125.50, rating: 5.0, completedTasks: 35, role: 'student' },
  { id: 7, name: 'Sami Järvinen', email: 'sami@opisto.fi', avatar: '👨', balance: 62.00, rating: 4.7, completedTasks: 18, role: 'student' },
  { id: 8, name: 'Tero Mäkelä', email: 'tero@opisto.fi', avatar: '👨', balance: 91.00, rating: 4.5, completedTasks: 25, role: 'student' },
  { id: 9, name: 'Hanna Lahtinen', email: 'hanna@opisto.fi', avatar: '👩', balance: 38.75, rating: 4.4, completedTasks: 11, role: 'student' },
  { id: 10, name: 'Opiston Admin', email: 'admin@opisto.fi', avatar: '🔐', balance: 0, rating: 5.0, completedTasks: 0, role: 'admin' },
];

export const demoApartments = [
  {
    id: 1,
    name: 'Asuntola 1',
    residents: 45,
    rooms: 15,
    image: '🏠',
    description: 'Moderni asuntola keskellä opistoa',
    x: 30,
    y: 40,
  },
  {
    id: 2,
    name: 'Asuntola 2',
    residents: 38,
    rooms: 13,
    image: '🏢',
    description: 'Hiljainen asuntola lähellä kirjastoa',
    x: 70,
    y: 35,
  },
  {
    id: 3,
    name: 'Asuntola 3',
    residents: 52,
    rooms: 18,
    image: '🏘️',
    description: 'Suurin asuntola kampuksella',
    x: 50,
    y: 70,
  },
  {
    id: 4,
    name: 'Asuntola 4',
    residents: 28,
    rooms: 10,
    image: '🏗️',
    description: 'Uusimmat tilat ja laitteet',
    x: 20,
    y: 65,
  },
];

export const demoTasks = [
  { id: 1, title: '🧹 Huoneen siivous', desc: 'Huoneen siivoaminen', apt: 'Asuntola 1', room: '104', price: 2, deadline: 'Tänään klo 18', status: 'available', createdBy: 1 },
  { id: 2, title: '🍽️ Tiskit', desc: 'Astikoiden pesu', apt: 'Asuntola 2', room: '201', price: 3, deadline: 'Tänään klo 20', status: 'available', createdBy: 2 },
  { id: 3, title: '🗑️ Roskien vienti', desc: 'Roskien kuljetus', apt: 'Asuntola 1', room: '102', price: 1, deadline: 'Tänään klo 20', status: 'reserved', createdBy: 3, reservedBy: 4 },
  { id: 4, title: '👕 Pyykkien vienti', desc: 'Pyykkien kuljetus pyykkitupaan', apt: 'Asuntola 3', room: '301', price: 2, deadline: 'Huomenna klo 15', status: 'available', createdBy: 5 },
  { id: 5, title: '🧹 Kylpyhuoneen siivous', desc: 'Kylpyhuoneen puhdistus', apt: 'Asuntola 2', room: '202', price: 3, deadline: 'Huomenna klo 12', status: 'available', createdBy: 6 },
  { id: 6, title: '🛁 Saunan siivous', desc: 'Saunan pesu ja puhdistus', apt: 'Asuntola 1', room: 'Sauna', price: 4, deadline: 'Perjantaina', status: 'available', createdBy: 1 },
  { id: 7, title: '📚 Kirjastokierroksesta kerääminen', desc: 'Kirjastosta tarpeelliset asiat', apt: 'Asuntola 4', room: '405', price: 2, deadline: 'Tänään', status: 'reserved', createdBy: 7, reservedBy: 2 },
  { id: 8, title: '🧺 Liinavaatteiden pesu', desc: 'Lakanoiden ja liinavaatteiden pesu', apt: 'Asuntola 3', room: '302', price: 5, deadline: 'Viikonloppuna', status: 'available', createdBy: 8 },
  { id: 9, title: '🍃 Pihan puhdistus', desc: 'Näkyvien roskat pois', apt: 'Asuntola 2', room: 'Piha', price: 2, deadline: 'Perjantaina', status: 'available', createdBy: 9 },
  { id: 10, title: '🪟 Ikkunoiden pesu', desc: 'Huoneen ikkunoiden pesu', apt: 'Asuntola 1', room: '103', price: 3, deadline: 'Huomenna', status: 'available', createdBy: 3 },
  { id: 11, title: '🧹 Käytävän siivous', desc: 'Käytävän imurointi ja pesu', apt: 'Asuntola 4', room: 'Käytävä', price: 2, deadline: 'Tänään', status: 'available', createdBy: 4 },
  { id: 12, title: '🍳 Ruokarasvien poistaminen', desc: 'Liesien puhdistus', apt: 'Asuntola 3', room: 'Keittiö', price: 3, deadline: 'Tänään klo 19', status: 'available', createdBy: 5 },
  { id: 13, title: '🚪 Ovien puhdistus', desc: 'Kaikkien huoneen ovien puhdistus', apt: 'Asuntola 1', room: '105', price: 1, deadline: 'Huomenna', status: 'available', createdBy: 6 },
  { id: 14, title: '🧖 Sähköpostissa ilmoitukset', desc: 'Sähköpostissa mainostetun tehtävän suoritus', apt: 'Asuntola 2', room: '205', price: 4, deadline: 'Tänään', status: 'reserved', createdBy: 7, reservedBy: 1 },
  { id: 15, title: '🌡️ Radiatorien puhdistus', desc: 'Radiatorien pölyjen poistaminen', apt: 'Asuntola 4', room: '504', price: 2, deadline: 'Viikonloppuna', status: 'available', createdBy: 8 },
];

export const demoEvents = [
  {
    id: 1,
    title: '🏐 Lentopalloa illalla',
    description: 'Tulee mielenkiintoinen lentopalloilta! Kaikille avoin peli.',
    location: 'Urheiluhalli',
    date: 'Tänään',
    time: '19:00',
    participants: 12,
    organizer: 'Mikko',
    image: '🏐',
  },
  {
    id: 2,
    title: '🔥 Nuotioilta',
    description: 'Viikon päätto vietetään nuotiolla. Hyviä välipaloja ja hyvää seuraa!',
    location: 'Rantasauna',
    date: 'Perjantaina',
    time: '20:00',
    participants: 8,
    organizer: 'Anna',
    image: '🔥',
  },
  {
    id: 3,
    title: '🎮 Pelailta',
    description: 'Pelikonsolissa ja tietokoneilla. FIFA, Fortnite ja muuta hauskaa.',
    location: 'Oleskelutila',
    date: 'Lauantaina',
    time: '18:00',
    participants: 15,
    organizer: 'Jukka',
    image: '🎮',
  },
  {
    id: 4,
    title: '🎬 Elokuvailta',
    description: 'Kotimaisen elokuvan katselu yhdessä. Popcorni ja juoma tarjolla!',
    location: 'Aula',
    date: 'Sunnuntaina',
    time: '19:30',
    participants: 20,
    organizer: 'Liisa',
    image: '🎬',
  },
  {
    id: 5,
    title: '🍕 Pizza-ilta',
    description: 'Yhteinen pizza-juhlat. Kaikille omansa valinneet.',
    location: 'Ruokasali',
    date: 'Maanantaina',
    time: '18:00',
    participants: 35,
    organizer: 'Petri',
    image: '🍕',
  },
  {
    id: 6,
    title: '🎤 Lauluilta',
    description: 'Karaoken ääressa. Älä häpeä, kaikki osallistuvat!',
    location: 'Baarila',
    date: 'Keskiviikkona',
    time: '20:00',
    participants: 18,
    organizer: 'Maria',
    image: '🎤',
  },
  {
    id: 7,
    title: '🚴 Pyöräretki',
    description: 'Maalaistielle pyörän. Mukaan pullot ja snäksiä.',
    location: 'Pääportaali',
    date: 'Perjantai-iltapäivä',
    time: '15:00',
    participants: 10,
    organizer: 'Sami',
    image: '🚴',
  },
  {
    id: 8,
    title: '⚽ Futis-ottelu',
    description: 'Asuntola 1 vs Asuntola 2. Ottelun jälkeen juhlat.',
    location: 'Urheilukenttä',
    date: 'Sunnuntai-iltapäivä',
    time: '14:00',
    participants: 22,
    organizer: 'Tero',
    image: '⚽',
  },
];

export const demoAnnouncements = [
  {
    id: 1,
    title: '⚠️ Pyykkitupa pois käytöstä',
    description: 'Pyykkitupa on huollossa keskiviikkona ja torstaina. Palvelu palautuu perjantaina normaaliksi.',
    date: '2024-01-15',
    publisher: 'Opiston henkilökunta',
    isImportant: true,
    isPinned: true,
    image: '🔧',
  },
  {
    id: 2,
    title: '🍽️ Ruokalan aukiolo muuttuu',
    description: 'Ruokala sulkeutuu tämän viikon perjantaina klo 18 henkilöstöpäivän takia.',
    date: '2024-01-14',
    publisher: 'Opiston keittiö',
    isImportant: false,
    isPinned: true,
    image: '🍽️',
  },
  {
    id: 3,
    title: '📚 Kirjasto sulkeutuu aikaisemmin',
    description: 'Kirjasto sulkeutuu klo 17 perjantaina johtuen henkilöstöpalaverita.',
    date: '2024-01-13',
    publisher: 'Opiston kirjasto',
    isImportant: false,
    isPinned: false,
    image: '📚',
  },
  {
    id: 4,
    title: '🌡️ Lämmitys vikaantui',
    description: 'Asuntola 3:n lämmitys on huollossa. Lämmitys palautuu parhaimmillaan illalla.',
    date: '2024-01-12',
    publisher: 'Kiinteistöhoito',
    isImportant: true,
    isPinned: false,
    image: '🌡️',
  },
  {
    id: 5,
    title: '🎓 Opinto-ohjaaja tapaamiseen',
    description: 'Muista varata aika opinto-ohjaajaasi kanssa neuvotteluun. Aika menee nopeasti!',
    date: '2024-01-11',
    publisher: 'Opinto-ohjaus',
    isImportant: false,
    isPinned: false,
    image: '🎓',
  },
  {
    id: 6,
    title: '💉 Rokotuskampanja',
    description: 'Terveyshoitaja on paikalla maanantaina ja tiistaina rokotukselle ilmoittautumisesta.',
    date: '2024-01-10',
    publisher: 'Terveydenhoito',
    isImportant: false,
    isPinned: false,
    image: '💉',
  },
];
